# BEGIN_KITTY_THEME
# Atelier Lakeside Dark
include current-theme.conf
# END_KITTY_THEME
#

# padding
window_margin_width 10

# transparency
background_opacity 0.95

# cursor trail (looks sick)
cursor_trail 200

# tabs styling
tab_bar_style powerline

# borders
active_border_color #00ffcc


# Split right (side-by-side)
#map alt+shift+d launch --location=hsplit

# Split down (top-bottom)
#map alt+shift+s launch --location=vsplit

# Always force horizontal split (left/right)
map alt+shift+s launch --location=hsplit --cwd=current

# Always force vertical split (top/bottom)
map alt+shift+d launch --location=vsplit --cwd=current

map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

map alt+shift+q new_tab

map alt+shift+w close_window

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9

map alt+shift+left resize_window narrower
map alt+shift+right resize_window wider
map alt+shift+up resize_window taller
map alt+shift+down resize_window shorter

enabled_layouts splits
