[gdrive]
type = drive
scope = drive
team_drive = 

[gdrive2]
type = drive
scope = drive
team_drive = 


# NOTE: Run "rclone config reconnect gdrive:" to re-authenticate
# NOTE: Run "rclone config reconnect gdrive2:" to re-authenticate
